<section class="simpleCallout" sizcache="0" sizset="19">
<h1>More Information</h1>
<ul class="singleLine" sizcache="0" sizset="19">
<li><a href="http://recreation.du.edu/clubsports/">Club Sports</a> 
</li><li><a href="http://recreation.du.edu/membership/?main=16&amp;main2=183&amp;main3=0">Coors Fitness Center</a> 
</li><li><a href="http://recreation.du.edu/recreation/?main=2&amp;main2=76&amp;main3=0">Intramural Sports</a> </li></ul>
</section>
<p class="reset">&nbsp;</p>
