<article class="callOutBanner">
	<a href="#"><img src="img/A6d_points.png" width="243" height="25" alt="Pioneer Pride" /></a>
	<section class="callOutContent">
		<ul>
			<li><a href="#">Blackboard</a> (Online Course Material)</li>
			<li><a href="#">MyPeak</a> (Penrose Library services)</li>
			<li><a href="#">My Web</a> (registration and grades)</li>
			<li><a href="#">Blackboard</a> (Online Course Material)</li>
		</ul>
	</section>
	<footer class="callOutBannerFtr">
		<img src="img/A6d_points2.png" width="243" height="155" alt="DU Swimmer" />
	</footer>
</article>

<p class="reset">&nbsp;</p>
