<article class="simpleCallout">
  <h1>Quick Links</h1>
  <ul class="singleLine">
	<li>
	  <h2>Contact Us</h2>
	  <address itemscope="true" itemtype="http://data-vocabulary.org/Organization">
		<span itemprop="name">University Communications<br/> 
		University of Denver</span><br/>
		<span itemprop="address" itemscope="true" itemtype="http://data-vocabulary.org/Address">
		  <span itemprop="street-address">Mary Reed Building Room 122 and 022</span>,<br/>
		  <span itemprop="street-address">2199 S. University Blvd.</span>,<br/>
		  <span itemprop="locality">Denver</span>, <span itemprop="region">CO</span> <span itemprop="postal-cod">80208</span><br/>
		</span>
		Phone: <span itemprop="tel">303-871-2711</span><br/>
		Fax: <span itemprop="tel">303.871.4880</span><br/>
		<a href="mailto:ucomm@du.edu">E-mail</a><br/>
		Url: <a href="www.du.edu" itemprop="url">www.du.edu</a>
		<span itemprop="geo" itemscope="true" itemtype="http://data-vocabulary.org/Geo"> 
		  <meta itemprop="latitude" content="39.677646" /> 
		  <meta itemprop="longitude" content="-104.959387" /> 
		</span>
	  </address>
	</li>
	<li><a href="http://www.du.edu/engage/student/studentmain.html" title="Civic Engagement and Service Learning">Civic Engagement and Service Learning</a></li>
	<li><a href="http://www.alumni.du.edu/Learn/CE/" title="Continuing Education for Alumni">Continuing Education for Alumni</a></li>
  </ul>
</article>
<p class="reset">&nbsp;</p>
