<section class="imageColContent">
<h4>Ut enim ad minima veniam</h4>
<p>Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
	<ul>
<li>Content</li>
<li>Content</li>
<li>Content</li>
<li>Content</li>
</ul>
<p>Column Content</p>
<p>Column Content</p>
<p>Column Content</p>
</section>

<figure class="imageColRight">
		<img src="/_resources/snippets/img/A1_01.jpg" class="framedPhotoDefault" />
		<img src="/_resources/snippets/img/A1_01.jpg" class="framedPhotoDefault" />
		<img src="/_resources/snippets/img/A1_01.jpg" class="framedPhotoDefault" />
</figure>  

<p class="reset">&nbsp;</p>
