<article class="photoContentContainerRight">
	<figure class="framedPhotoRight">
		<img src="/_resources/snippets/img/A1_01.jpg" />
	</figure>
	<section class="photoContentLeft">
		<h4>Learning</h4>
		<div class="subContent">
			<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
<ul>
<li>&nbsp;</li>
<li>&nbsp;</li>
<li>&nbsp;</li>
<li>&nbsp;</li>
</ul>
		</div>
	</section>
</article>

<p class="reset">&nbsp;</p>
