<ul class="profiles">
<li>
    <article>
        <header>
        <img alt="Temporary Profile Picture" border="0" class="profile" height="148" src="img/NSM_staffImg.jpg" width="126"/> 
        <h4 class="profile"><a href="/Homepage/index.xml" title="Profile, Name">Some Profile Name</a></h4>
        </header>
        <section>
        Assistant Professor<br/>
        Phone: 123.456.7890<br/>
        Email: <a href="mailto:some.profile@du.edu">Some.profile@du.edu</a><br/>
        <br/>
        <a href="/Homepage/index.xml" title="More Information for Some Profile">More Information</a><br/>
        <br/>
        <br/>
        <br/>
        </section>
        <section>
        <h3>Background</h3>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eros urna, scelerisque at rhoncus sed, mollis nec dui. Proin nec imperdiet dui. Vestibulum arcu felis, dignissim at placerat nec, sodales ut arcu. Sed ullamcorper lacinia odio, at lacinia diam facilisis ac. Donec luctus ante nec ipsum venenatis sagittis. Nulla suscipit.
        </section>
        <section>
        <h3>Interests</h3>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eros urna, scelerisque at rhoncus sed, mollis nec dui. Proin nec imperdiet dui. Vestibulum arcu felis, dignissim at placerat nec, sodales ut arcu. Sed ullamcorper lacinia odio, at lacinia diam facilisis ac. Donec luctus ante nec ipsum venenatis sagittis. Nulla suscipit. 
        </section>
        <section>
        <h3>Publications</h3>
        Title of the article<br/>
        <a href="http://www.publication.com/article" title="Link to the article">www.publication.com/article</a>
        </section>
    </article>
</li>

<li>
Use snippets to add individual staff profile here, or delete this message
</li>

</ul>

<p class="reset">&nbsp;</p>
