<section class="threeSubCol">					
	
	<article class="vertCol">
		<figcaption>Column 1 figcaption</figcaption>
		<figure class="framedPhotoDefault">
			<img src="/_resources/snippets/img/A1_01.jpg" />
		</figure>
		<p>Sub Content Paragraph and List... quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
		<ul>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
		</ul>
		<section class="expandList">
			<article class="expandListItem">
				<h5>ExpandableList</h5>
				<div class="expandListItemContent">
					<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
					<ul>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
					</ul>
				</div>
			</article>
			<p>&nbsp;</p>
		</section>
	</article>
	<article class="vertCol">
		<figcaption>Column 2 figcaption</figcaption>
		<figure class="framedPhotoDefault">
			<img src="/_resources/snippets/img/A1_01.jpg" />
		</figure>
		<p>Sub Content Paragraph and List... quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
		<ul>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
		</ul>
		<section class="expandList">
			<article class="expandListItem">
				<h5>ExpandableList</h5>
				<div class="expandListItemContent">
					<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
					<ul>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
					</ul>
				</div>
			</article>
			<p>&nbsp;</p>
		</section>
	</article>
	<article class="vertCol last">
		<figcaption>Column 3 figcaption</figcaption>
		<figure class="framedPhotoDefault">
			<img src="/_resources/snippets/img/A1_01.jpg" />
		</figure>
		<p>Sub Content Paragraph and List... quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
		<ul>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
			<li>Content</li>
		</ul>
		<section class="expandList">
			<article class="expandListItem">
				<h5>ExpandableList</h5>
				<div class="expandListItemContent">
					<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p>
					<ul>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
						<li>Content</li>
					</ul>
				</div>
			</article>
			<p>&nbsp;</p>
		</section>
	</article>
</section>


<p class="reset">&nbsp;</p>
