<figure>
	<ul id="gallery">
		<li class="show"><img src="http://www.du.edu/media/images/banners/banner_studentemail.jpg" alt="" width="985" height="270" /></li>
		<li><img src="http://www.du.edu/media/images/banners/banner_emergency.jpg" alt="" width="985" height="270" /></li>
		<li><img src="http://www.du.edu/media/images/banners/banner_facstaffemail.jpg" alt="" width="985" height="270" /></li>
	</ul>
</figure>

<figure class="slideControl">
	<ul>
		<li class="slideMarker1 slideSelected">.</li>
		<li class="slideMarker2">.</li>
		<li class="slideMarker3">.</li>
		<li id="playPause">
			<a href="#" id="btn-pause"><img src="/_resources/snippets/img/btn_pause.png" width="10" height="12" alt="Pause" /></a> 
			<a href="#" id="btn-play"><img src="/_resources/snippets/img/btn_play.png" width="10" height="12" alt="Play" /></a>
		</li>
	</ul>
</figure>
