<!--include path explore/transforming.pcf (banner attribute) -> attribute read by general.xsl -> which then loads this custom banner html-->
<style>
	#heroBackground {width:985px; height:400px; margin:0 auto; background-image:url('/media/images/campaigns/transformations/condoleezza/campaign_herobase.jpg'); background-repeat:no-repeat; background-size:985px 400px; box-shadow:0 0 10px #000000;}
	#transformSlideDiv {position:absolute; top:0px; left:50%; width:985px; height:100%; margin-left:-493px;}
	#transformImage {float:left; margin:0; padding:0;}
	#transformText {float:right; width:300px; margin:20px 10px 20px 0; color:#FFF; font-size:0.8em;}
	#transformText h3 {font-size:1.2em;}
	#transformText ul {padding:0 0 20px 20px;}
	#transformLinks {clear:both; float:right; margin-top:-10px; font-size:0.75em; line-height:1.167em;}
	#transformLinks img {padding-right:10px;}
	#transformLinks div {vertical-align:top; margin-right:30px; display:inline-block;}
	#transformLinks a {text-decoration:underline;}
	#transformLinks a:hover {text-decoration:none;}
</style>
<div id="heroBackground">&nbsp;</div>
<div id="transformSlideDiv">
  <div id="transformImage"><img src="/media/images/campaigns/transformations/condoleezza/campaign_heroid.png" alt="Condoleeza Rice" width="663" height="326" /></div>
    <div id="transformText">
      <h3>Condoleezza Rice</h3>
      <ul>
        <li>Enrolled at the University of Denver to pursue studies in classical music.</li>
        <li>A single international relations course changed her worldview.</li>
        <li>The rest is history.</li>
      </ul>
      <p>Students come to the University of Denver to find their true purpose. They go on to careers of distinction and lives of meaning.</p>
    </div>
  <div id="transformLinks">
    <img src="/media/images/campaigns/transformations/campaign_herochevron.png" alt="view" width="17" height="34" />
    <div style="margin-right:10px; width: 120px;"><a href="/korbel/index.html">Korbel School of International Relations</a></div>
    <img src="/media/images/campaigns/transformations/campaign_herochevron.png" alt="view" width="17" height="34" />
    <div style="padding-top: 10px;"><a href="/apply/index.html">Apply</a></div>
    <img src="/media/images/campaigns/transformations/campaign_herochevron.png" alt="view" width="17" height="34" />
    <div style="width:100px; padding-top:5px;"><a href="/ascend/index.html">Support the University</a></div>
  </div>
</div>
