
          <ul>
            <li><a href="http://www.facebook.com/uofdenver/" target="_blank" title="link to university of denver facebook" class="footerFacebook">
				The University of Denver on Facebook</a></li>
            <li><a href="http://twitter.com/uofdenver/" target="_blank" title="link to university of denver twitter" class="footerTwitter">
				The University of Denver on Twitter</a></li>
            <li><a href="http://www.flickr.com/photos/uofdenver/" target="_blank" title="link to university of denver flickr" class="footerFlickr">
				The University of Denver on Flickr</a></li>
            <li><a href="http://www.youtube.com/uofdenver/" target="_blank" title="link to university of denver youtube" class="footerYoutube">
				The University of Denver on YouTube</a></li>
          </ul>
