
       <nav id="learnFooter" class="footerLinks">
          <h1><a href="/learn/index.html" title="university learn">Learn</a></h1>
          <div class="footerBorder">
            <h2><a href="/learn/undergraduates/index.html" title="undergraduates">Undergraduates</a></h2>
            <ul>
              <li><a href="/learn/undergraduates/degreeprograms.html" title="undergraduate degree programs">Degree Programs</a></li>

              <li><a href="/learn/undergraduates/schoolsandcolleges.html" title="undergraduate schools and colleges">Schools &amp; Colleges</a></li>
				<li><a href="/abroad/index.html" title="undergraduate study abroad">Study Abroad</a></li>
              <li><a href="/directory/" title="undergraduate faculty and staff">Faculty &amp; Staff</a></li>
            </ul>
            <h2><a href="/learn/graduates/index.html" title="graduates">Graduates</a></h2>

            <ul>
              <li><a href="/learn/graduates/degreeprograms/index.html" title="graduate degree programs">Degree Programs</a></li>
              <li><a href="/learn/graduates/schoolsandcolleges.html" title="graduate schools and colleges">Schools &amp; Colleges</a></li>
              <li><a href="/learn/graduates/graduateresearch.html" title="graduate research">Graduate Research</a></li>
              <li><a href="/directory/" title="graduate faculty and staff">Faculty &amp; Staff</a></li>

            </ul>
          </div>
        </nav>

        <nav id="liveFooter" class="footerLinks">
          <h1><a href="/live/index.html" title="university live">Live</a></h1>
          <div class="footerBorder">
            <ul>
              <li><a href="/live/housing.html" title="university live housing">Housing</a></li>

              <li><a href="/live/denvercolorado.html" title="university live denver and colorado">Denver &amp; Colorado</a></li>
              <li><a href="/live/clubsandorganizations.html" title="university live clubs and organizations">Clubs &amp; Organizations</a></li>
              <li><a href="/live/athleticsandrecreation.html" title="university live athletics and recreation">Athletics &amp; Recreation</a></li>
			  <li><a href="http://sqc.wpengine.com/events-listing/" title="Calendar of 150th anniversary events">Event Series</a></li>
              <li><a href="http://ducal.du.edu/" title="university live events">Events</a></li>

              <li><a href="http://volunteer.du.edu/" title="university volunteer">Volunteer</a></li>
              <li><a href="http://www.du.edu/emergency/index.html" title="emergency preparedness">Emergency Preparedness</a></li>
              <li><a href="http://www.denverpioneers.com/" title="denver pioneers official athletics site"><img alt="Denver Athletics"  src="/_resources/images/btns/btn_athletics.png"/></a></li>
            </ul>
          </div>
        </nav>

        <nav id="exploreFooter" class="footerLinks">

          <h1><a href="/explore/index.html" title="university explore">Explore</a></h1>
          <div class="footerBorder">
            <ul>
              <li><a href="/explore/about/index.html" title="university About DU">About DU</a></li>
				<li><a href="/explore/transforming.html" title="university explore transforming pioneers">Transforming Pioneers</a></li>
			  <li><a href="/explore/campus/index.html" title="university explore du campus">DU Campus</a></li>
              <li><a href="/explore/studentprofiles.html" title="university explore student profiles">Student Profiles</a></li>
              <li><a href="/explore/factsandfigures.html" title="university explore facts and figures">Facts &amp; Figures</a></li>
              <li><a href="/explore/historyandtraditions.html" title="university explore history and tradition">History &amp; Traditions</a></li>
			  <li><a href="/ascend/index.html" target="_self" title="Give to DU">Give to DU</a></li>
              <li><a href="/explore/visionandvalues.html" title="university explore vision and values">Vision &amp; Values</a></li>
              <li><a href="/explore/artsandculture/index.html" title="university explore arts and culture">Arts &amp; Culture</a></li>
              <li><a href="/explore/researchandinnovation/index.html" title="university explore research and innovation">Research &amp; Innovation</a></li>
              <li><a href="http://www.du.edu/communityvisitors/index.html" title="university explore community and visitors">Community &amp; Visitors</a></li>
				<li><a href="http://videocast.du.edu/" title="university explore videos" target="_blank">University Videos</a></li>
            </ul>
          </div>
        </nav>

        <nav id="applyFooter" class="footerLinks">
          <h1><a href="/apply/index.html" title="university apply">Apply</a></h1>

          <div class="footerBorder">
            <h2><a href="/apply/undergraduates/index.html" title="undergraduates">Undergraduates</a></h2>
            <ul>
              <li><a href="http://www.du.edu/apply/admission/index.html" title="undergraduate admission">Admission</a></li>
              <li><a href="http://www.du.edu/financialaid/index.html" title="undergraduate tuition and aid">Tuition &amp; Financial Aid</a></li>
            </ul>

            <h2><a href="/apply/graduates/index.html" title="graduates">Graduates</a></h2>
            <ul>
              <li><a href="/apply/graduates/index.html" title="graduate admission">Admission</a></li>
				<li><a href="http://www.du.edu/financialaid/graduate/index.html" title="graduate tuition and aid">Tuition &amp; Financial Aid</a></li>
            </ul>
          </div>

        </nav>

        <nav id="newsFooter" class="footerLinks">
          <h1><a href="http://magazine.du.edu" title="the magazine">DU News</a></h1>
          <div class="footerBorder">
            <ul>
              <li><a href="http://magazine.du.edu" title="the magazine">DU Magazine</a></li>
              <li><a href="http://www.du.edu/marcomm/media-relations/index.html" title="du media resources">DU Media Resources</a></li>
              <li><a href="http://www.duclarion.com/" title="the clarion">The Clarion</a></li>
            </ul>
          </div>
        </nav>
