        <header id="globalHeader" class="compact">
          <div id="globalHeaderContent">
            <h1 class="logo"><a href="/index.html" title="link to university of denver home page"><img src="http://www.du.edu/_resources/images/nav/logo2.gif" alt="University of Denver" width="140" height="40"/></a></h1>
            <section class="searchContainer">
              
              <nav id="globalUtilities">
 			<ol>
                  <li><a href="?logout=" title="logout of intranet"><img src="http://www.du.edu/_resources/images/intranet/icon_lock.png" alt="lock image" width="14"/> Logout</a></li>
                </ol>
              </nav>
            </section>
            <div class="clear">&nbsp;</div>
          </div>
        </header>
