<header id="globalHeader">
<div id="globalHeaderContent">
<h1 class="logo" style="padding-right:0;"><a title="link to university of denver home page" href="/index.html"><img src="/_resources/images/nav/primary_nav_logo.gif" alt="University of Denver" width="219" height="59" /></a></h1>
<nav id="mobile_menu"><ol>
<li id="mainNav"><a>Menu</a></li>
<li id="mobileLink"><a href="http://m.du.edu/">Mobile</a></li>
<li id="search"><a>Search</a></li>
</ol></nav><nav id="globalNav" style="margin-left:0;"><ol>
<li class="nav_01"><a title="link to prospective students" href="/prospectivestudents/index.html">Prospective Students</a></li>
<li class="nav_02"><a title="link to current students" href="/currentstudents/index.html">Current Students</a></li>
<li class="nav_03"><a title="link to faculty and staff" href="/facultystaff/index.html">Faculty &amp; Staff</a></li>
<li class="nav_04"><a title="link to alumni" href="http://www.du.edu/alumni/index.html">Alumni</a></li>
<li class="nav_05"><a title="link to parents and families" href="/parentsfamilies/index.html">Parents &amp; Families</a></li>
</ol></nav>
<section class="searchContainer" style="width:200px; padding-right:15px;"><form style="float:right;" action="http://search.du.edu/search" method="get" name="g2009search"><fieldset><input type="hidden" value="du_collection" name="site" /> <input type="hidden" value="du_frontend" name="client" /> <input type="hidden" value="du_frontend" name="proxystylesheet" /> <input type="hidden" value="xml_no_dtd" name="output" /> <input type="hidden" name="lr" /> <input type="hidden" value="utf8" name="ie" /> <input type="hidden" value="utf8" name="oe" /> <input class="clearField" dir="ltr" type="search" maxlength="255" placeholder="Search DU" title="Search DU" required name="q" /> <input class="btnSearch" type="image" alt="Go" src="/_resources/images/btns/btn_search_go.gif" name="go" /></fieldset></form><nav id="globalUtilities" style="clear:both; float:right; font-size:11px;"><ol>
<li><a title="Donate to University" href="/ascend/index.html">Give to DU</a>&nbsp;|</li>
<li><a title="link to university directory" href="/directory/">Directory</a>&nbsp;|</li>
<li><a title="link to a-z directory" href="/utilities/az/index.html">A-Z</a>&nbsp;|</li>
<li><a title="link to site map" href="/utilities/sitemap/index.html">Site Map</a></li>
</ol></nav></section>
<div class="clear">&nbsp;</div>
</div>
</header>
