<div id="wowslider-container1">
<div class="ws_images">
<ul>
<li><img id="wows1_1" title="" src="/media/images/homecoming_slider.jpg" alt="Homecoming" width="711" height="415" />At a special sesquicentennial edition of <a href="http://alumni.du.edu/s/1150/interior2013/index.aspx?sid=1150&amp;pgid=7765&amp;gid=1&amp;cid=12440&amp;ecid=12440&amp;post_id=0">Homecoming and Family Weekend</a>, Oct. 30-Nov. 2, Pioneers of all generations will come together to celebrate.</li>
<li><img id="wows1_2" title="" src="/media/images/balloon_slider.jpg" alt="Weather Balloon" width="711" height="415" />By launching data-collecting weather balloons, students studying <a href="/nsm/departments/geography/index.html">geography and the environment</a> learn about atmospheric processes.</li>
<li><img id="wows1_3" title="" src="/media/images/sesquicentennialvintage_slider.jpg" alt="150 years" width="711" height="415" />Throughout the University's <a href="http://sesquicentennial.du.edu">150-year history</a>, our students have formed a dynamic community on campus.</li>
<li><img id="wows1_4" title="" src="/media/images/slideruhall.jpg" alt="University Hall" width="711" height="415" />The University of Denver's<a href="https://www.youtube.com/watch?v=-mucyBhu4r0&amp;feature=share&amp;list=PL707A42B8E0F90167"> tree-lined campus</a> provides the perfect backdrop for engaged learning and quiet reflection.</li>
<li><img id="wows1_5" title="" src="/_resources/images/slider_du_home/duhomepage_sponsorslider.jpg" alt="Sesquicentennial" width="711" height="415" />Checkout our Sesquicentennial sponsors:<br /><a href="http://www.denverpost.com/" target="_blank" rel="nofollow">The Denver Post</a><br /><a href="https://www.pscu.org/" target="_blank" rel="nofollow">Public Service Credit Union</a></li>
<li><img id="wows1_6" title="" src="/media/images/homepage_styrclass.jpg" alt="Campus Green" width="711" height="415" />With the start of fall quarter, the University of Denver <a href="http://magazine.du.edu/campus-community/diverse-high-achieving-class-2018">welcomes the Class of 2018</a> to campus—one of the most diverse classes in our history.</li>
</ul>
</div>
</div>
<script type="text/javascript" src="/_resources/scripts/plugins/wow-slider/engine1/wowslider.js"></script>
<script type="text/javascript" src="/_resources/scripts/plugins/wow-slider/engine1/script.js"></script>
