<ul>
<li><a title="link to university contacts and directions" href="/utilities/contactsanddirections/index.html">Contacts &amp; Directions</a>&nbsp;|&nbsp;</li>
<li><a title="link to university maps" href="/utilities/maps/index.html">Maps</a>&nbsp;|&nbsp;</li>
<li><a title="link to university jobs" href="https://dujobs.silkroad.com/" target="_blank">Jobs</a>&nbsp;|&nbsp;</li>
<li><a title="University Giving" href="http://www.du.edu/give/index.html" target="_blank">Giving</a>&nbsp;|&nbsp;</li>
<li><a title="University of Denver Mobile Site" href="http://m.du.edu">DU Mobile Site</a>&nbsp;|&nbsp;</li>
<li><a title="link to university site map" href="/utilities/sitemap/index.html">Site Map</a></li>
</ul>
